#!/bin/bash
set -e && cd ./scripts
source kitty.sh
source install.sh
source bugFix.sh

# fix_apt
# python3 login.py
# install_fanyi
fix_apt

# TODO: arg:
# -i install    install [package name]
# -u update     update  [package name]
# -s settings   config some application
# -e edit       edit rec script file
# -l login      login school net

# tldr -u

# upgrade ls
# sudo rm /usr/bin/ls && sudo ln -s `which exa` /usr/bin/ls
