lastupdatecheck: 0
recentrepos:
- /data/data/com.termux/files/home/dotfiles
- /data/data/com.termux/files/home/.config/nvim
- /data/data/com.termux/files/home/project/Neovim/Trans.nvim
- /data/data/com.termux/files/home/Desktop/nvim
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
