lastupdatecheck: 0
recentrepos:
- /home/zoran/dotfiles
- /home/zoran/project/Neovim/Trans.nvim
- /home/zoran/.config/nvim
- /home/zoran/notes
- /home/zoran/project/Neovim/Trans.nvim/wiki
- /home/zoran/project/Cpp/project/parser
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
