lastupdatecheck: 0
recentrepos:
- /home/zoran/dotfiles
- /home/zoran/project/Neovim/Trans.nvim
- /home/zoran/.local/share/nvim/lazy/ChatGPT.nvim
- /home/zoran/.config/nvim
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
