lastupdatecheck: 0
recentrepos:
- /home/zoran/dotfiles
- /home/zoran/.config/nvim
- /home/zoran/myConfig/blog
- /home/zoran/dotfiles/background
- /home/zoran/.config/nvim/custom/Trans.nvim
- /home/zoran/dotfiles/config/awesome
- /home/zoran/.local/share/nvim/lazy/flash.nvim
- /home/zoran/dotfiles/config/surfingkeys-conf
- /home/zoran/myConfig/misc/awesome
- /home/zoran/.config/nvim/custom/snippet_lua
- /home/zoran/.local/share/nvim/lazy/hlchunk.nvim
- /home/zoran/project/Cpp/project/Principle-of-compilation-from-scratch/cpp_lexer_generator
- /home/zoran/.config/nvim/custom/Trans.nvim/wiki
- /home/zoran/.config/nvim/minimal_conf
- /home/zoran/project/Cpp/project/Principle-of-compilation-from-scratch
startuppopupversion: 5
customcommandshistory:
- ' "baidu",'
hidecommandlog: false
