lastupdatecheck: 0
recentrepos:
- /home/zoran/dotfiles
- /home/zoran/project/Cpp/project/Principle-of-compilation-from-scratch/cpp_lexer_generator
- /home/zoran/project/Cpp/project/Principle-of-compilation-from-scratch
- /home/zoran/myConfig/blog
- /home/zoran/.config/nvim
- /home/zoran/.config/nvim/custom/Trans.nvim
- /home/zoran/.config/awesome/lib/awesome-cyclefocus
- /home/zoran/dotfiles/config/surfingkeys-conf
- /home/zoran/.config/nvim/custom/Trans.nvim/wiki
startuppopupversion: 5
customcommandshistory:
- ' "baidu",'
hidecommandlog: false
