lastupdatecheck: 0
recentrepos:
- /home/zoran/dotfiles
- /home/zoran/.config/nvim
- /home/zoran/project/Cpp_Server
- /home/zoran/project/neovim/Trans
- /home/zoran/Rust/Hello-Rust
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
