lastupdatecheck: 0
recentrepos:
- /home/zoran/dotfiles
- /home/zoran/.config/nvim
- /home/zoran/.config/nvim/custom/Trans.nvim
- /home/zoran/.config/nvim/custom/Trans.nvim/wiki
- /home/zoran/project/Cpp/project/Principle-of-compilation-from-scratch
- /home/zoran/notes/study-notes
- /home/zoran/project/Cpp/folk/EmmyLua
startuppopupversion: 5
customcommandshistory:
- ' "baidu",'
hidecommandlog: false
